# Generated by Django 5.2 on 2025-05-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="response",
            field=models.TextField(blank=True, null=True),
        ),
    ]
