# Generated by Django 5.2 on 2025-05-02 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0002_question_response"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="response",
        ),
    ]
