# Generated by Django 5.2 on 2025-05-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0003_remove_question_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="response",
            field=models.TextField(blank=True, null=True),
        ),
    ]
