# Generated by Django 5.2 on 2025-05-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0004_question_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewsession",
            name="cached_feedback",
            field=models.TextField(blank=True, null=True),
        ),
    ]
